### ISSUE TITLE
Add 1.10 commands

### ISSUE THREAD

**Issue by Aiidoneus** [Slind14/Wiki#114]
Thinking about the best way to go about this and not quite sure what path to go down for this. What if we modify https://github.com/Slind14/Wiki/blob/master/docs/source/Knowledge_Base/commands.rst to include the commands. Maybe make a new section? 
Thoughts?

**Comment by bigbluu722** [comment]
New section for 1.10 donor commands would be ideal imo. Also removing the server restart vote commands would be a good call too now looking on the list. 
-V

**Comment by Sir-Will** [comment]
Added seperate list: https://github.com/Slind14/Wiki/blob/master/docs/source/Knowledge_Base/commands_1.10.rst
