### ISSUE TITLE
Updating the MineYourMind Information Page

### ISSUE THREAD

**Issue by Aiidoneus** [Slind14/Wiki#178]
[This](http://docs.mym.li/en/latest/MineYourMind/index.html) page could use a complete overhaul.

- [x] Staff Section (Would like to see individual boxes for each staff category or something neater)

- [x] Backups (Remove and update filler text)

- [x] About MindYourMind (Complete overhaul)

**Comment by Column01** [comment]
Not sure what we want to do for the About MineYourMind section. We kind of already cover it in the introduction section at the top and it would probably be a minor tweak of that.

**Comment by Formdude** [comment]
Any updates @Aiidoneus I don't think the about: mineyourmind section is there any more. I'm not sure if I can self-assign it as soon as you add the section, but I'll have to do it whenever I'm not too busy at school.
