### ISSUE TITLE
Linux Install too complex

### ISSUE THREAD

**Issue by Column01** [Slind14/Wiki#181]
I believe the linux install is too complex for the average user. I had a 50 year old man come to me today and ask me how to install it. After I made myself familiar with the way it was supposed to be installed, it took me 2 hours to get it all ready for him since he had never used terminal this much.

I propose we make a shell script to do a lot of the brunt work for us. Find the files, make the directories, move them, ETC. It would help a lot. The issue comes when I have to make it. I do not know enough about Linux to formulate a coherent and universal shell script to perform these tasks. I know enough to get the job done on a single machine, but not on all other machines.

I have cleaned up the install instructions in PR #180 but I believe there needs to be more done.

**Comment by Slind14** [comment]
hmm, this is not mandatory. These are optional steps to make it look nicer (so it has an icon and is found under programs..)

**Comment by Column01** [comment]
Since its optional and I don't see how I could make something for this that could be supported by MyM, I'm gonna close this out. Reopen it if you want me to work on it
