### ISSUE TITLE
Split indexes into Categorized Files

### ISSUE THREAD

**Issue by Column01** [Slind14/Wiki#185]
## Sections to be split
- [x] FAQ
- [x] Launcher Info
- [x] Performance guide

These need to be split into individual pages. Will make it more convenient for future editing/viewing. Take the [knowledge base](https://github.com/Slind14/Wiki/tree/master/docs/source/Knowledge_Base) for example, all are split into individual files which makes it way easier to edit.

**Comment by Formdude** [comment]
Self-assigning, doing performance guide first then launcher info after

**Comment by Column01** [comment]
@Formdude Use the referenced commit above as a guide on how you need to do it.

**Comment by Formdude** [comment]
#185 Does this work?
